### ISSUE TITLE
could you provide minimal working app example?

### ISSUE THREAD

**Issue by luntik2012** [OlivierLDff/QtStaticCMake#4]
I'm getting this when using your file:

```sh
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x5f): undefined reference to `qt_static_plugin_QMinimalIntegrationPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x7f): undefined reference to `qt_static_plugin_QOffscreenIntegrationPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x8f): undefined reference to `qt_static_plugin_QSvgIconPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x9f): undefined reference to `qt_static_plugin_QSvgPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0xcf): undefined reference to `qt_static_plugin_QTuioTouchPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0xdf): undefined reference to `qt_static_plugin_QVirtualKeyboardPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x10f): undefined reference to `qt_static_plugin_QWindowsDirect2DIntegrationPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x12f): undefined reference to `qt_static_plugin_QXdgDesktopPortalThemePlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x1ff): undefined reference to `qt_static_plugin_QtVirtualKeyboardHangulPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x20f): undefined reference to `qt_static_plugin_QtVirtualKeyboardOpenWnnPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x21f): undefined reference to `qt_static_plugin_QtVirtualKeyboardPinyinPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x22f): undefined reference to `qt_static_plugin_QtVirtualKeyboardTCImePlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_plugin_import.cpp.obj):qml_hello_world_plugin_import.cpp:(.text.startup+0x23f): undefined reference to `qt_static_plugin_QtVirtualKeyboardThaiPlugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_qml_plugin_import.cpp.obj):qml_hello_world_qml_plugin_import.cpp:(.text.startup+0xf): undefined reference to `qt_static_plugin_QtQuick2Plugin()'
CMakeFiles/qml_hello_world.dir/objects.a(qml_hello_world_qml_plugin_import.cpp.obj):qml_hello_world_qml_plugin_import.cpp:(.text.startup+0x1f): undefined reference to `qt_static_plugin_QtQuick2WindowPlugin()'
```

```cmake
cmake_minimum_required(VERSION 3.5)

project(qml_hello_world LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
SET(QT_USE_QTPLUGIN TRUE)
set(CMAKE_AUTOSTATICPLUGINS ON)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# QtCreator supports the following variables for Android, which are identical to qmake Android variables.
# Check http://doc.qt.io/qt-5/deployment-android.html for more information.
# They need to be set before the find_package(Qt5 ...) call.

#if(ANDROID)
#    set(ANDROID_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/android")
#    if (ANDROID_ABI STREQUAL "armeabi-v7a")
#        set(ANDROID_EXTRA_LIBS
#            ${CMAKE_CURRENT_SOURCE_DIR}/path/to/libcrypto.so
#            ${CMAKE_CURRENT_SOURCE_DIR}/path/to/libssl.so)
#    endif()
#endif()

find_package(Qt5 COMPONENTS Core Quick QuickControls2 Qml REQUIRED)
include(QtStaticCMake.cmake)

if(ANDROID)
    add_library(qml_hello_world SHARED
      main.cpp
      qml.qrc
    )
else()
    add_executable(qml_hello_world
      main.cpp
      qml.qrc
    )
endif()

target_compile_definitions(qml_hello_world
  PRIVATE $<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:QT_QML_DEBUG>)
#target_link_libraries(qml_hello_world
#  PRIVATE Qt5::Core Qt5::Quick Qt5::QuickControls2 Qt5::Qml)
qt5_use_modules(${PROJECT_NAME}
    Core
    Gui
    Qml
    Quick
    QuickControls2
    Concurrent
    Widgets
    )

qt_generate_plugin_import(${PROJECT_NAME}
#  OUTPUT "example_plugin_import.cpp"
#  OUTPUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}
  VERBOSE)

qt_generate_qml_plugin_import(${PROJECT_NAME}
#  QML_DIR "/path/to/qtsdk"
  QML_SRC ${CMAKE_SOURCE_DIR}
#  OUTPUT "example_qml_plugin_import.cpp"
#  OUTPUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}
  VERBOSE)

qt5_import_plugins(${PROJECT_NAME}
    INCLUDE
    qtquick2plugin
    Qt5::QtQuickControls2Plugin
    Qt5::QtQuick2Plugin
    Qt5::QtQuickLayoutsPlugin
    Qt5::QtQuickTemplates2Plugin
    Qt5::QtQuickWindowPlugin
    Qt5::QtQuick2WindowPlugin
    Qt5::QWindowsIntegrationPlugin

)

```

**Comment by OlivierLDff** [comment]
You can find an example here: https://github.com/OlivierLDff/QaterialGallery/blob/master/CMakeLists.txt
```
if(QT_STATIC)
    qt_generate_qml_plugin_import(${QATERIALGALLERY_TARGET} QML_SRC ${CMAKE_CURRENT_SOURCE_DIR}/qml VERBOSE)
    qt_generate_plugin_import(${QATERIALGALLERY_TARGET} VERBOSE)
endif(QT_STATIC)
```
Maybe `qt5_use_modules(${PROJECT_NAME} Svg VirtualKeyboard ...)`

I will check your repo tomorrow and try stuff.

**Comment by OlivierLDff** [comment]
Ok, so i was using this script for qt ios, and the `-u _qt_registerPlatformPlugin` was doing the trick only for qt ios. But doesn't seem to be supported on other platform.
What is happening is that the plugin libraries aren't linked with your target.
`qt5_import_plugins` in [Qt5.14](https://doc.qt.io/qt-5/qtcore-cmake-qt5-import-plugins.html) seems to address this issue. 
I think this problem can be fixed with a `target_link_libraries(target Qt5::QSvgPlugin)` for each plugin.
I modified `QtStaticCMake.cmake` to handle this:
``` cmake
foreach(PLUGIN ${QT_STATIC_QML_DEPENDENCIES_PLUGINS})
  file(APPEND ${QT_STATIC_QML_PLUGIN_SRC_FILE} "Q_IMPORT_PLUGIN(${PLUGIN});\n")
  set(PLUGIN_LIBRARY Qt5::${PLUGIN})
  target_link_libraries(${QT_STATIC_TARGET} ${PLUGIN_LIBRARY})
endforeach()
```
And:
``` cmake
# ...
file(APPEND ${QT_STATIC_PLUGIN_SRC_FILE} "Q_IMPORT_PLUGIN(${PLUGIN_NAME});\n")
set(PLUGIN_LIBRARY Qt5::${PLUGIN_NAME})
target_link_libraries(${QT_STATIC_TARGET} ${PLUGIN_LIBRARY})
# ...
```

But now i'm having issue with CMake unable to find `QtQuick*` plugin.
Svg, MinimalIntegration, etc... error are gone.
I'm compiling qt5.14 to try the `qt5_import_plugins` and see what it does. Qt cmake support is greatly improving at each release.
What is the version of qt you are using?

**Comment by luntik2012** [comment]
I'm already using ```qt5_use_modules``` to link QuickControls2 and others and ```qt5_import_plugins```, look at this

https://github.com/luntik2012/qml_hello_world/blob/master/CMakeLists.txt

But I don't know names of plugins, so just written something like ```Qt5::QtQuickControls2Plugin```.

Also, ```QWindowsIntegrationPlugin``` works because it has .prl file in qt dir, when qquick2 has only .a and .cmake files (don't know how it should work, no docs).

I'm using mxe version of qt 5.14.2

**Comment by OlivierLDff** [comment]
Ok so i fork your project and i made it work. Took me a while to figure out.
https://github.com/OlivierLDff/qml_hello_world_static

I cleaned every file to have a minimum working project.

Can you say if this is working for you?

I used Qt5.14.2, i had a bug to fix in qt sources with missing Qt5ZLib. You can see the bug report here that have been fixed : https://bugreports.qt.io/browse/QTBUG-79547
https://codereview.qt-project.org/c/qt/qtbase/+/296134/2/mkspecs/features/data/cmake/Qt5BasicConfig.cmake.in#410

You need to set ` add_library(Qt5::Zlib INTERFACE IMPORTED)` inside `lib/cmake/Qt5ZlibConfig.cmake` and remove the following `setproperty(...)` command.

**Comment by luntik2012** [comment]
I get this
```sh
CMake Error at CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!

```

because of `NO_CMAKE_SYSTEM_PATH`

After removing `NO_CMAKE_SYSTEM_PATH` (or specifying CMAKE_INSTALL_PREFIX) I get this
```sh
== Using MXE wrapper: /home/nikita/git/mxe/usr/bin/x86_64-w64-mingw32.static-cmake
     - cmake version 3.15.4
     - warnings for unused CMAKE_POLICY_DEFAULT variables can be ignored
== Using MXE toolchain: /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
== Using MXE runresult: /home/nikita/git/mxe/usr/share/cmake/modules/TryRunResults.cmake
== Adding "-DCMAKE_BUILD_TYPE=Release"
loading initial cache file /home/nikita/git/mxe/usr/share/cmake/modules/TryRunResults.cmake
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /home/nikita/git/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static-g++
-- Check for working CXX compiler: /home/nikita/git/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Qt SDK Root: /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5
-- OUTPUT not specified, default to qml_hello_world_plugin_import.cpp
-- OUTPUT not specified, default to /tmp/qml_hello_world_static/build
-- ------ QtStaticCMake Plugin Generate Configuration ------
-- TARGET   : qml_hello_world
-- OUTPUT      : qml_hello_world_plugin_import.cpp
-- OUTPUT_DIR  : /tmp/qml_hello_world_static/build
-- ------ QtStaticCMake Plugin Generate End Configuration ------
-- Generate qml_hello_world_plugin_import.cpp in /tmp/qml_hello_world_static/build
-- Force link to qml plugin Qt5::QGifPlugin
-- Force link to qml plugin Qt5::QICNSPlugin
-- Force link to qml plugin Qt5::QICOPlugin
-- Force link to qml plugin Qt5::QJp2Plugin
-- Force link to qml plugin Qt5::QJpegPlugin
-- Force link to qml plugin Qt5::QMinimalIntegrationPlugin
-- Force link to qml plugin Qt5::QMngPlugin
-- Force link to qml plugin Qt5::QOffscreenIntegrationPlugin
-- Force link to qml plugin Qt5::QSvgIconPlugin
-- Force link to qml plugin Qt5::QSvgPlugin
-- Force link to qml plugin Qt5::QTgaPlugin
-- Force link to qml plugin Qt5::QTiffPlugin
-- Force link to qml plugin Qt5::QTuioTouchPlugin
-- Force link to qml plugin Qt5::QVirtualKeyboardPlugin
-- Force link to qml plugin Qt5::QWbmpPlugin
-- Force link to qml plugin Qt5::QWebpPlugin
-- Force link to qml plugin Qt5::QWindowsDirect2DIntegrationPlugin
-- Force link to qml plugin Qt5::QWindowsIntegrationPlugin
-- Force link to qml plugin Qt5::QXdgDesktopPortalThemePlugin
-- Force link to qml plugin Qt5::QGenericEnginePlugin
-- Force link to qml plugin Qt5::QDebugMessageServiceFactory
-- Force link to qml plugin Qt5::QLocalClientConnectionFactory
-- Force link to qml plugin Qt5::QQmlDebugServerFactory
-- Force link to qml plugin Qt5::QQmlDebuggerServiceFactory
-- Force link to qml plugin Qt5::QQmlInspectorServiceFactory
-- Force link to qml plugin Qt5::QQmlNativeDebugConnectorFactory
-- Force link to qml plugin Qt5::QQmlNativeDebugServiceFactory
-- Force link to qml plugin Qt5::QQmlPreviewServiceFactory
-- Force link to qml plugin Qt5::QQmlProfilerServiceFactory
-- Force link to qml plugin Qt5::QQuickProfilerAdapterFactory
-- Force link to qml plugin Qt5::QTcpServerConnectionFactory
-- Force link to qml plugin Qt5::QtVirtualKeyboardHangulPlugin
-- Force link to qml plugin Qt5::QtVirtualKeyboardOpenWnnPlugin
-- Force link to qml plugin Qt5::QtVirtualKeyboardPinyinPlugin
-- Force link to qml plugin Qt5::QtVirtualKeyboardTCImePlugin
-- Force link to qml plugin Qt5::QtVirtualKeyboardThaiPlugin
-- Force link to qml plugin Qt5::QWindowsVistaStylePlugin
-- qml_hello_world plugin dependencies:
-- QGifPlugin
-- QICNSPlugin
-- QICOPlugin
-- QJp2Plugin
-- QJpegPlugin
-- QMinimalIntegrationPlugin
-- QMngPlugin
-- QOffscreenIntegrationPlugin
-- QSvgIconPlugin
-- QSvgPlugin
-- QTgaPlugin
-- QTiffPlugin
-- QTuioTouchPlugin
-- QVirtualKeyboardPlugin
-- QWbmpPlugin
-- QWebpPlugin
-- QWindowsDirect2DIntegrationPlugin
-- QWindowsIntegrationPlugin
-- QXdgDesktopPortalThemePlugin
-- QGenericEnginePlugin
-- QDebugMessageServiceFactory
-- QLocalClientConnectionFactory
-- QQmlDebugServerFactory
-- QQmlDebuggerServiceFactory
-- QQmlInspectorServiceFactory
-- QQmlNativeDebugConnectorFactory
-- QQmlNativeDebugServiceFactory
-- QQmlPreviewServiceFactory
-- QQmlProfilerServiceFactory
-- QQuickProfilerAdapterFactory
-- QTcpServerConnectionFactory
-- QtVirtualKeyboardHangulPlugin
-- QtVirtualKeyboardOpenWnnPlugin
-- QtVirtualKeyboardPinyinPlugin
-- QtVirtualKeyboardTCImePlugin
-- QtVirtualKeyboardThaiPlugin
-- QWindowsVistaStylePlugin
-- Add /tmp/qml_hello_world_static/build/qml_hello_world_plugin_import.cpp to qml_hello_world sources
-- QML_DIR not specified, default to /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml
-- OUTPUT not specified, default to qml_hello_world_qml_plugin_import.cpp
-- OUTPUT not specified, default to /tmp/qml_hello_world_static/build
-- ------ QtStaticCMake Qml Generate Configuration ------
-- TARGET          : qml_hello_world
-- QML_DIR         : /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml
-- QML_SRC         : /tmp/qml_hello_world_static
-- OUTPUT          : qml_hello_world_qml_plugin_import.cpp
-- OUTPUT_DIR      : /tmp/qml_hello_world_static/build
-- EXTRA_PLUGIN    : QtQuickVirtualKeyboardPlugin;QtQuickVirtualKeyboardSettingsPlugin;QtQuickVirtualKeyboardStylesPlugin;QmlFolderListModelPlugin;QQuickLayoutsPlugin
-- ------ QtStaticCMake Qml Generate End Configuration ------
-- Get Qml Plugin dependencies for qml_hello_world. qmlimportscanner path is /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmlimportscanner. RootPath is /tmp/qml_hello_world_static and importPath is /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml.
-- qml_hello_world qml plugin dependencies:
-- QtQuick2Plugin
-- QtQuick2WindowPlugin
-- Generate qml_hello_world_qml_plugin_import.cpp in /tmp/qml_hello_world_static/build
-- Add /tmp/qml_hello_world_static/build/qml_hello_world_qml_plugin_import.cpp to qml_hello_world sources
CMake Warning at QtStaticCMake.cmake:200 (message):
  Fail to find QtQuick2Plugin for release build (release or debug library not
  available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:217 (message):
  Fail to find QtQuick2Plugin for debug build (release or debug library not
  available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:200 (message):
  Fail to find WindowPlugin for release build (release or debug library not
  available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:217 (message):
  Fail to find WindowPlugin for debug build (release or debug library not
  available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:200 (message):
  Fail to find QtQuickVirtualKeyboardPlugin for release build (release or
  debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:217 (message):
  Fail to find QtQuickVirtualKeyboardPlugin for debug build (release or debug
  library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:200 (message):
  Fail to find QtQuickVirtualKeyboardSettingsPlugin for release build
  (release or debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:217 (message):
  Fail to find QtQuickVirtualKeyboardSettingsPlugin for debug build (release
  or debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:200 (message):
  Fail to find QtQuickVirtualKeyboardStylesPlugin for release build (release
  or debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:217 (message):
  Fail to find QtQuickVirtualKeyboardStylesPlugin for debug build (release or
  debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:200 (message):
  Fail to find QmlFolderListModelPlugin for release build (release or debug
  library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:217 (message):
  Fail to find QmlFolderListModelPlugin for debug build (release or debug
  library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:200 (message):
  Fail to find QQuickLayoutsPlugin for release build (release or debug
  library not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


CMake Warning at QtStaticCMake.cmake:217 (message):
  Fail to find QQuickLayoutsPlugin for debug build (release or debug library
  not available)
Call Stack (most recent call first):
  CMakeLists.txt:50 (qt_generate_qml_plugin_import)


-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0017
    CMAKE_POLICY_DEFAULT_CMP0020


-- Build files have been written to: /tmp/qml_hello_world_static/build

```

May be I'll try linux static qt built by hands

**Comment by OlivierLDff** [comment]
Can check what do you have in your qml/ folder of the qt sdk?
Are the library there?
My script will be looking for libraries inside `/home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml`.
I did my test with qt5.14 on windows compiled with msvc.

```
/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat
configure -nomake examples -nomake tests -opensource -static -confirm-license -prefix ../qt-msvc2019-static/ -platform win32-msvc -skip webengine  -debug
nmake
nmake install
```

**Comment by OlivierLDff** [comment]
I made some improvements that i pushed in this repository (i also updated the qml_hello_world_static repository.

Now i'm using more information from `qmlimportscanner`. Try to uncomment those line to see what is returned from the exec:

``` cmake
# Dump Json File for debug
if(QT_STATIC_VERBOSE)
    message(STATUS "qmlimportscanner result: ${QT_STATIC_QML_DEPENDENCIES_JSON}")
endif()
```

For example i have something like that:
``` json
{
    "classname": "QtQuick2Plugin",
    "name": "QtQuick",
    "path": "C:/qt/qml/QtQuick.2",
    "plugin": "qtquick2plugin",
    "relativePath": "QtQuick.2",
    "type": "module",
    "version": "2.14"
}
```

**Comment by luntik2012** [comment]
Still didn't build static qt by hands, but cloned your repo and got such json:

```json
[
    {
        "classname": "QtQuick2Plugin",
        "name": "QtQuick",
        "path": "/home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick.2",
        "plugin": "qtquick2plugin",
        "relativePath": "QtQuick.2",
        "type": "module",
        "version": "2.14"
    },
    {
        "classname": "QtQuick2WindowPlugin",
        "name": "QtQuick.Window",
        "path": "/home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Window.2",
        "plugin": "windowplugin",
        "relativePath": "QtQuick/Window.2",
        "type": "module",
        "version": "2.14"
    }
]
```

Error remains the same, full log:

```sh
$ x86_64-w64-mingw32.static-cmake -DCMAKE_PREFIX_PATH=/home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/ ..
== Using MXE wrapper: /home/nikita/git/mxe/usr/bin/x86_64-w64-mingw32.static-cmake
     - cmake version 3.15.4
     - warnings for unused CMAKE_POLICY_DEFAULT variables can be ignored
== Using MXE toolchain: /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
== Using MXE runresult: /home/nikita/git/mxe/usr/share/cmake/modules/TryRunResults.cmake
== Adding "-DCMAKE_BUILD_TYPE=Release"
loading initial cache file /home/nikita/git/mxe/usr/share/cmake/modules/TryRunResults.cmake
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /home/nikita/git/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static-g++
-- Check for working CXX compiler: /home/nikita/git/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Qt SDK Root: /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5
-- OUTPUT not specified, default to QQuickStaticHelloWorld_plugin_import.cpp
-- OUTPUT not specified, default to /tmp/QQuickStaticHelloWorld/build
-- ------ QtStaticCMake Plugin Generate Configuration ------
-- TARGET   : QQuickStaticHelloWorld
-- OUTPUT      : QQuickStaticHelloWorld_plugin_import.cpp
-- OUTPUT_DIR  : /tmp/QQuickStaticHelloWorld/build
-- ------ QtStaticCMake Plugin Generate End Configuration ------
-- Generate QQuickStaticHelloWorld_plugin_import.cpp in /tmp/QQuickStaticHelloWorld/build
-- Force link to qml plugin Qt5::QGifPlugin
-- Force link to qml plugin Qt5::QICNSPlugin
-- Force link to qml plugin Qt5::QICOPlugin
-- Force link to qml plugin Qt5::QJp2Plugin
-- Force link to qml plugin Qt5::QJpegPlugin
-- Force link to qml plugin Qt5::QMinimalIntegrationPlugin
-- Force link to qml plugin Qt5::QMngPlugin
-- Force link to qml plugin Qt5::QOffscreenIntegrationPlugin
-- Force link to qml plugin Qt5::QSvgIconPlugin
-- Force link to qml plugin Qt5::QSvgPlugin
-- Force link to qml plugin Qt5::QTgaPlugin
-- Force link to qml plugin Qt5::QTiffPlugin
-- Force link to qml plugin Qt5::QTuioTouchPlugin
-- Force link to qml plugin Qt5::QVirtualKeyboardPlugin
-- Force link to qml plugin Qt5::QWbmpPlugin
-- Force link to qml plugin Qt5::QWebpPlugin
-- Force link to qml plugin Qt5::QWindowsDirect2DIntegrationPlugin
-- Force link to qml plugin Qt5::QWindowsIntegrationPlugin
-- Force link to qml plugin Qt5::QXdgDesktopPortalThemePlugin
-- Force link to qml plugin Qt5::QGenericEnginePlugin
-- Force link to qml plugin Qt5::QDebugMessageServiceFactory
-- Force link to qml plugin Qt5::QLocalClientConnectionFactory
-- Force link to qml plugin Qt5::QQmlDebugServerFactory
-- Force link to qml plugin Qt5::QQmlDebuggerServiceFactory
-- Force link to qml plugin Qt5::QQmlInspectorServiceFactory
-- Force link to qml plugin Qt5::QQmlNativeDebugConnectorFactory
-- Force link to qml plugin Qt5::QQmlNativeDebugServiceFactory
-- Force link to qml plugin Qt5::QQmlPreviewServiceFactory
-- Force link to qml plugin Qt5::QQmlProfilerServiceFactory
-- Force link to qml plugin Qt5::QQuickProfilerAdapterFactory
-- Force link to qml plugin Qt5::QTcpServerConnectionFactory
-- Force link to qml plugin Qt5::QtVirtualKeyboardHangulPlugin
-- Force link to qml plugin Qt5::QtVirtualKeyboardOpenWnnPlugin
-- Force link to qml plugin Qt5::QtVirtualKeyboardPinyinPlugin
-- Force link to qml plugin Qt5::QtVirtualKeyboardTCImePlugin
-- Force link to qml plugin Qt5::QtVirtualKeyboardThaiPlugin
-- Force link to qml plugin Qt5::QWindowsVistaStylePlugin
-- QQuickStaticHelloWorld plugin dependencies:
-- QGifPlugin
-- QICNSPlugin
-- QICOPlugin
-- QJp2Plugin
-- QJpegPlugin
-- QMinimalIntegrationPlugin
-- QMngPlugin
-- QOffscreenIntegrationPlugin
-- QSvgIconPlugin
-- QSvgPlugin
-- QTgaPlugin
-- QTiffPlugin
-- QTuioTouchPlugin
-- QVirtualKeyboardPlugin
-- QWbmpPlugin
-- QWebpPlugin
-- QWindowsDirect2DIntegrationPlugin
-- QWindowsIntegrationPlugin
-- QXdgDesktopPortalThemePlugin
-- QGenericEnginePlugin
-- QDebugMessageServiceFactory
-- QLocalClientConnectionFactory
-- QQmlDebugServerFactory
-- QQmlDebuggerServiceFactory
-- QQmlInspectorServiceFactory
-- QQmlNativeDebugConnectorFactory
-- QQmlNativeDebugServiceFactory
-- QQmlPreviewServiceFactory
-- QQmlProfilerServiceFactory
-- QQuickProfilerAdapterFactory
-- QTcpServerConnectionFactory
-- QtVirtualKeyboardHangulPlugin
-- QtVirtualKeyboardOpenWnnPlugin
-- QtVirtualKeyboardPinyinPlugin
-- QtVirtualKeyboardTCImePlugin
-- QtVirtualKeyboardThaiPlugin
-- QWindowsVistaStylePlugin
-- Add /tmp/QQuickStaticHelloWorld/build/QQuickStaticHelloWorld_plugin_import.cpp to QQuickStaticHelloWorld sources
-- QML_DIR not specified, default to /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml
-- OUTPUT not specified, default to QQuickStaticHelloWorld_qml_plugin_import.cpp
-- OUTPUT not specified, default to /tmp/QQuickStaticHelloWorld/build
-- ------ QtStaticCMake Qml Generate Configuration ------
-- TARGET          : QQuickStaticHelloWorld
-- QML_DIR         : /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml
-- QML_SRC         : /tmp/QQuickStaticHelloWorld/qml
-- OUTPUT          : QQuickStaticHelloWorld_qml_plugin_import.cpp
-- OUTPUT_DIR      : /tmp/QQuickStaticHelloWorld/build
-- EXTRA_PLUGIN    : QtQuickVirtualKeyboardPlugin;QtQuickVirtualKeyboardSettingsPlugin;QtQuickVirtualKeyboardStylesPlugin;QmlFolderListModelPlugin;QQuickLayoutsPlugin
-- ------ QtStaticCMake Qml Generate End Configuration ------
-- Get Qml Plugin dependencies for QQuickStaticHelloWorld. qmlimportscanner path is /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmlimportscanner. RootPath is /tmp/QQuickStaticHelloWorld/qml and importPath is /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml.
-- qmlimportscanner result: [
    {
        "classname": "QtQuick2Plugin",
        "name": "QtQuick",
        "path": "/home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick.2",
        "plugin": "qtquick2plugin",
        "relativePath": "QtQuick.2",
        "type": "module",
        "version": "2.14"
    },
    {
        "classname": "QtQuick2WindowPlugin",
        "name": "QtQuick.Window",
        "path": "/home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Window.2",
        "plugin": "windowplugin",
        "relativePath": "QtQuick/Window.2",
        "type": "module",
        "version": "2.14"
    }
]
-- Generate QQuickStaticHelloWorld_qml_plugin_import.cpp in /tmp/QQuickStaticHelloWorld/build
-- Add /tmp/QQuickStaticHelloWorld/build/QQuickStaticHelloWorld_qml_plugin_import.cpp to QQuickStaticHelloWorld sources
-- QtQuick2Plugin Release : Found /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick.2/libqtquick2plugin.a
-- QtQuick2Plugin Debug : Found /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick.2/libqtquick2plugin.a (debug library not available, use release as fallback)
-- QtQuick2WindowPlugin Release : Found /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Window.2/libwindowplugin.a
-- QtQuick2WindowPlugin Debug : Found /home/nikita/git/mxe/usr/x86_64-w64-mingw32.static/qt5/qml/QtQuick/Window.2/libwindowplugin.a (debug library not available, use release as fallback)
CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:239 (message):
  Fail to find QtQuickVirtualKeyboardPlugin for release build (release or
  debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:257 (message):
  Fail to find QtQuickVirtualKeyboardPlugin for debug build (release or debug
  library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:239 (message):
  Fail to find QtQuickVirtualKeyboardSettingsPlugin for release build
  (release or debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:257 (message):
  Fail to find QtQuickVirtualKeyboardSettingsPlugin for debug build (release
  or debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:239 (message):
  Fail to find QtQuickVirtualKeyboardStylesPlugin for release build (release
  or debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:257 (message):
  Fail to find QtQuickVirtualKeyboardStylesPlugin for debug build (release or
  debug library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:239 (message):
  Fail to find QmlFolderListModelPlugin for release build (release or debug
  library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:257 (message):
  Fail to find QmlFolderListModelPlugin for debug build (release or debug
  library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:239 (message):
  Fail to find QQuickLayoutsPlugin for release build (release or debug
  library not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


CMake Warning at build/_deps/qtstaticcmake-src/QtStaticCMake.cmake:257 (message):
  Fail to find QQuickLayoutsPlugin for debug build (release or debug library
  not available)
Call Stack (most recent call first):
  CMakeLists.txt:48 (qt_generate_qml_plugin_import)


-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0017
    CMAKE_POLICY_DEFAULT_CMP0020


-- Build files have been written to: /tmp/QQuickStaticHelloWorld/build

```

**Comment by OlivierLDff** [comment]
Ok i know why it's failing now.
Json is returning real name for QtQuick2Plugin and QtQuick2WindowPlugin, so library are found.

Then it's looking for let's say QQuickLayoutsPlugin, in windows i have a `qquicklayoutsplugin.lib` so it's finding it with the `find_library` command.
But on your system the library file is `libqquicklayoutsplugin.a`.

You should retry with last version of QtStaticCMake, i fixed it in 11d676961805cd8233010947050db378ae8c416a

**Comment by luntik2012** [comment]
I've udpated your repo, renamed plugins names to lower register like this:

```cmake
qt_generate_qml_plugin_import(QQuickStaticHelloWorld
    QML_SRC ${CMAKE_CURRENT_SOURCE_DIR}/qml
    EXTRA_PLUGIN
      qtquickvirtualkeyboardplugin
      qtquickvirtualkeyboardsettingsplugin
      qtquickvirtualkeyboardstylesplugin
      qmlfolderlistmodelplugin
      qquicklayoutsplugin
    VERBOSE
  )
```

All those errors gone except this:

```sh
undefined reference to `QQmlWorkerScriptModule::registerQuickTypes()'
```

I've found `qt5/qml/QtQml/WorkerScript.2/libworkerscriptplugin.a` and added `workerscriptplugin` to `qt_generate_qml_plugin_import`. No cmake errors, but still have undefined reference error

**Comment by OlivierLDff** [comment]
`QQmlWorkerScriptModule::registerQuickTypes` should be in `libqt5qmlworkerscript.a` in `qt5/lib`
For plugin, you needed to put them lower case, it didn't work like i wrote them?
I should modify QtStaticCMake.cmake to use cmake's `string(TOLOWER <string1> <output variable>)`.

You can dump the content of you `libqt5qmlworkerscript.a` with `nm libqt5qmlworkerscript.a` to check that symbol is defined there.

This symbol is only defined for qt lower than 6.
From `qt/include/QtQmlWorkerScript/5.14.2/QtQmlWorkerScript/private/qqmlworkerscriptmodule_p.h`:

``` cpp
class Q_QMLWORKERSCRIPT_PRIVATE_EXPORT QQmlWorkerScriptModule
{
public:
#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
    static void registerQuickTypes();
#endif
    static void defineModule();
};
```

This module exist only from qt 5.14, i don't what it is for.

Maybe you can also try to remove this dependency from `target_link_libraries`

**Comment by luntik2012** [comment]
> Maybe you can also try to remove this dependency from target_link_libraries

I've used your repo and there was no such dependency in it. I've just got `undefined reference` and added it to `qt_generate_qml_plugin_import`, didn't help.

```sh
$ nm usr/x86_64-w64-mingw32.static/qt5/qml/QtQml/WorkerScript.2/libworkerscriptplugin.a | grep -i register
0000000000000000 r .pdata$_ZN23QtQmlWorkerScriptPlugin13registerTypesEPKc
0000000000000000 r .pdata$_ZThn16_N23QtQmlWorkerScriptPlugin13registerTypesEPKc
0000000000000000 t .text$_ZN23QtQmlWorkerScriptPlugin13registerTypesEPKc
0000000000000000 t .text$_ZThn16_N23QtQmlWorkerScriptPlugin13registerTypesEPKc
0000000000000000 r .xdata$_ZN23QtQmlWorkerScriptPlugin13registerTypesEPKc
0000000000000000 r .xdata$_ZThn16_N23QtQmlWorkerScriptPlugin13registerTypesEPKc
                 U _Z17qmlRegisterModulePKcii
0000000000000000 T _ZN23QtQmlWorkerScriptPlugin13registerTypesEPKc
0000000000000000 T _ZThn16_N23QtQmlWorkerScriptPlugin13registerTypesEPKc
                 U _Z21qRegisterResourceDataiPKhS0_S0_
                 U _Z23qUnregisterResourceDataiPKhS0_S0_
```
>  For plugin, you needed to put them lower case, it didn't work like i wrote them?

Yes, filename is `libqquicklayoutsplugin.a`, so we should link it like '-Lqquicklayoutsplugin', not in `CamelCase`.

You can take a look at my [fork](https://github.com/luntik2012/QQuickStaticHelloWorld) to see what I've tried

**Comment by OlivierLDff** [comment]
I wanted to say maybe you can remove :
``` cmake
if(TARGET Qt5::QmlWorkerScript)
  target_link_libraries(QQuickStaticHelloWorld Qt5::QmlWorkerScript)
endif()
```
I will compile my own qt static on linux to try and see if i can reproduce your issues.

**Comment by luntik2012** [comment]
sorry, didn't notice. I've commented it out and have the same error (`undefined reference`)

**Comment by OlivierLDff** [comment]
Ok my static build finished, good news or bad news i was able to reproduce your error.
I will try with another version of qt like 5.13.2.

I also fixed the lower case in last QtStaticCMake adf128634cbd49a70d2ca3786cf4035b630a9ceb.
So you can write plugin name in UpperCamelCase and just before calling `find_library` i'm transforming this variable `TOLOWER`

**Comment by OlivierLDff** [comment]
Ok so quick fix `target_link_libraries(QQuickStaticHelloWorld "/path/to/qt/5.14.2/gcc_64/lib/libQt5QmlWorkerScript.a")`

Somehow the `target_link_libraries(QQuickStaticHelloWorld Qt5::QmlWorkerScript)` doesn't seem to do it's job.

**Comment by OlivierLDff** [comment]
Ok i managed to make it work,
I moved : 
``` cmake
if(TARGET Qt5::QmlWorkerScript)
  target_link_libraries(QQuickStaticHelloWorld Qt5::QmlWorkerScript)
endif()
```

After qt_generate_qml_plugin_import.
This is very strange, this will need more investigation, because this might add a bug somewhere, either in qt's cmake, but most likely in my QtStaticCMake.cmake

Working commit is https://github.com/OlivierLDff/QQuickStaticHelloWorld/commit/90d90381c06f5a43a2d9df76b7f3b79b64a24414

But now i'm facing issue starting the app.
```
export QT_DEBUG_PLUGINS=1
./QQuickStaticHelloWorld
QFactoryLoader::QFactoryLoader() ignoring "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3" since plugins are disabled in static builds
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

I'm interested if you have the same, because i'm testing that with WSL, so maybe there is an issue there with x11 forwarding (which work when i'm linking to shared qt on wsl)

It strange  because the binary seems to be linked to x11 library
```
ldd ./QQuickStaticHelloWorld
        linux-vdso.so.1 (0x00007fffebd02000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f82dd130000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f82dd090000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f82dd06f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f82dce50000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f82dce40000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f82dce30000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f82dcc90000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f82dcb00000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f82dcae0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f82dc910000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f82de8dd000)
        libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f82dc8d0000)
        libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f82dc810000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f82dc6b0000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f82dc490000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f82dc460000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f82dc250000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f82dc040000)
        libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f82dc010000)
```

This should fix the error, but now i need to find where are those library
```
Q_IMPORT_PLUGIN(QXcbIntegrationPlugin)
Q_IMPORT_PLUGIN(QXcbGlxIntegrationPlugin)
```
EDIT:
Second try i did `sudo apt-get install libglfw3-dev libgles2-mesa-dev`, i recompiled qt and i have much more platform plugin, but still not xcb.

`Available platform plugins are: eglfs, linuxfb, minimalegl, minimal, offscreen, vnc, wayland-egl, wayland, webgl, wayland-egl, wayland, eglfs, linuxfb, minimalegl, minimal, offscreen, vnc, webgl. `

EDIT2:
After forcing xcb with `-qt-xcb` i get `ERROR: Feature 'xcb' was enabled, but the pre-condition 'features.thread && features.xkbcommon && libs.xcb' failed.`. So i have some missing dependency on my side. I'm currious if you managed to get it work.

**Comment by OlivierLDff** [comment]
I can confirm this work with on wsl debian with xcb.
* https://github.com/OlivierLDff/QQuickStaticHelloWorld/commit/f0963831ccf48b2eaf6943ecfdd5c507ab03d727
* https://github.com/OlivierLDff/QtStaticCMake/commit/ae5154bde93c5f6ad4849273937b478e0b636cb5

I build qt5.14.2 from source with
```
./configure -nomake examples -nomake tests -opensource -static -confirm-license -prefix ../build/5.14.2/gcc_64 -platform linux-g++ -qt-xcb 
-fontconfig -xkbcommon -sm -skip webengine -release
```
Somehow with thoose flags i dont have virtual keyboard stuff, so i have warning in cmake but at the end it work fine.

Hope this is working for you too?

Important : I updated `target_link_libraries` to use the more modern *keyword* function signature.
I also updated the example so match this policy. If you want to use plain `target_link_libraries` function signature, you need to `set(CMP0023 OLD)`
More info : https://cmake.org/cmake/help/v3.0/policy/CMP0023.html
